In [1]:
import numpy as np
import pandas as pd

In [2]:
#creation of numpy array with python object
a=np.array([[1,2,3],[4,5]],dtype="object")
print(a)
print('*********************')
#creation of numpy array with zeros
a=np.zeros((3,4))
print(a)
print('*********************')
#creation of numpy array with ones 
a=np.ones((3,4))
print(a)
print('*********************')
#creation of numpy array with arange
a=np.arange(1,10)
print(a)
print('*********************')
#creation of numpy array with identity matrix
a=np.eye(3,3)
print(a)

[list([1, 2, 3]) list([4, 5])]
*********************
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
*********************
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
*********************
[1 2 3 4 5 6 7 8 9]
*********************
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
#Array attributes
#dtype is an attribute in numpy which is used to get type of an array object
#shape is an attribute in numpy which is used to get shape of array which will have information about how many rows and columns are there (row,column)
#size is an attribute in numpy which will give total number of elements present in an array
#ndim is an attribute in numpy which will give dimension of an numpy array
a=np.array([[1,2,3],[4,5,6]])
print(a.dtype)
print('*********************')
print(a.shape)
print('*********************')
print(a.size)
print('*********************')
print(a.ndim)

int32
*********************
(2, 3)
*********************
6
*********************
2


In [4]:
#reshape function is used to change the shape of the array but the number of element should be same in new shape also
#flatten function is used to change the shape of the array to one dimension directly
#stack function is used to join the two array into single araay but major difference is it will join new array as new cell that is dimension will change,increase
#concatenate function will add another array rows in to an array that is dimension will not change another array rows will be concatenated to existed one from end
a=np.array([[1,2,3],[4,5,6]])
print(a.reshape((3,2)))
print('*********************')
print(a.flatten())
print('*********************')
print(np.stack((a,a)))
print('*********************')
print(np.concatenate((a,a)))

[[1 2]
 [3 4]
 [5 6]]
*********************
[1 2 3 4 5 6]
*********************
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
*********************
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [5]:
#array indexing and slicing 
a=np.array([[1,2,3],[4,5,6]])
# give the row and column index as such : [row,column]
print(a[1,1])
print('*********************')
# give range of rows and column indices as such :[starting row index: ending row index, starting column index: ending column index]
print(a[:,1:])
print('*********************')
# give boolean expression within square brackets to fetch some elements from array
print(a[a%2==0])

5
*********************
[[2 3]
 [5 6]]
*********************
[2 4 6]


In [6]:
#mathematical operations and statistical operation
a=np.array([[1,2,3],[4,5,6]])
# to add certain value to each element of array
print(a+2)
print('*********************')

# use np.sum() to get sum of all elements of array
print(np.sum(a))
print('*********************')

# use np.min() to get minimum element of the array
print(np.min(a))
print('*********************')

# use np.max() to get maximum element of the array
print(np.max(a))
print('*********************')

# use np.argmin() to get index of minimum element of the array
print(np.argmin(a))
print('*********************')

# use np.argmax() to get index of maximum element of the array
print(np.argmax(a))
print('*********************')

# use np.sqrt() to get square-root of all elements of the array
print(np.sqrt(a))
print('*********************')

# use np.exp() to get exponential of all elements of the array
print(np.exp(a))
print('*********************')

# use np.log() to get logarithm of all elements of the array
print(np.log(a))
print('*********************')

# use np.sin() to get sine of all elements of the array
print(np.sin(a))
print('*********************')

# use np.cos() to get cos of all elements of the array
print(np.cos(a))
print('*********************')

# use np.tan() to get tan of all elements of the array
print(np.tan(a))
print('*********************')

# use np.mean() to get mean of all elements of the array
print(np.mean(a))
print('*********************')

# use np.median() to get median of all elements of the array
print(np.median(a))
print('*********************')

# use np.var() to get variance of all elements of the array
print(np.var(a))
print('*********************')

# use np.cov() to get covariance of all elements of the array
print(np.cov(a))
print('*********************')

# use np.std() to get standard deviation of all elements of the array
print(np.std(a))
print('*********************')

# use np.dot() to get dot product of two arrays
b = np.array([[1,2],[3,4]])
print(np.dot(b,b))
print('*********************')

# use np.matmul() to get matrix multiplication of two arrays
print(np.matmul(b,b))
print('*********************')

# use np.linalg.norm() to get normalised distance of the array
print(np.linalg.norm(a))
print('*********************')

# use np.linalg.inv() to get inverse of the array
print(np.linalg.inv(b))
print('*********************')


[[3 4 5]
 [6 7 8]]
*********************
21
*********************
1
*********************
6
*********************
0
*********************
5
*********************
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
*********************
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
*********************
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
*********************
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
*********************
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
*********************
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
*********************
3.5
*********************
3.5
*********************
2.9166666666666665
*********************
[[1. 1.]
 [1. 1.]]
*********************
1.707825127659933
*********************
[[ 7 10]
 [15 22]]
*********************
[[ 7 10]
 [15 22]]
****

In [7]:
#array manipulation
a=np.array([[1,2,3],[4,5,6]])
#np.transpose() function will change the shape of array such that rows and columns are interchanged.
print(np.transpose(a))
print('*********************')

#np.hstack() will stack the arrays horizontally
print(np.hstack((a,a)))
print('*********************')

#np.vstack() will stack the arrays vertically
print(np.vstack((a,a)))
print('*********************')

#np.split() will split the array at specified index
print(np.split(a,[1]))
print('*********************')

#np.delete() will delete the elements at specified index
print(np.delete(a,[1,2]))
print('*********************')

#np.insert() will insert the elements at specified index
print(np.insert(a,2,10))
print('*********************')

#np.append() will append elements at the end
print(np.append(a,10))

[[1 4]
 [2 5]
 [3 6]]
*********************
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
*********************
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
*********************
[array([[1, 2, 3]]), array([[4, 5, 6]])]
*********************
[1 4 5 6]
*********************
[ 1  2 10  3  4  5  6]
*********************
[ 1  2  3  4  5  6 10]


In [8]:
#random generation
#np.random.rand() will generate a random numpy array of specified shape
print(np.random.rand(2,3))
print('*********************')

#np.random.randint() will generate a random numpy array of specified shape with values between the two numbers
print(np.random.randint(2,10,size=(2,2)))
print('*********************')

#np.random.choice() will select some number of arrays from already existing 1-dimensional array
print(np.random.choice(a.flatten(),size=4))

[[0.31763691 0.35864869 0.42993702]
 [0.03853219 0.16549812 0.49164129]]
*********************
[[5 3]
 [3 5]]
*********************
[6 5 4 4]


In [9]:
#sorting
a=np.array([[3,2,1],[6,4,5]])
#use np.sort() to sort the array in ascending order
print(np.sort(a))
print('*********************')

#np.argsort() will give the indexes of unsorted array
print(np.argsort(a))

[[1 2 3]
 [4 5 6]]
*********************
[[2 1 0]
 [1 2 0]]


In [10]:
#file input output
a=np.array([[3,2,1],[6,4,5]])

#np.save() function is used to save numpy array to a .npy file
np.save("numpy_pandas_revision.npy",a)

#np.savetxt() function is used to save numpy array to a .txt file. We need to give delimiter
np.savetxt("numpy_pandas_revision.txt",a,delimiter='---')

#np.load() function is used to load numpy array from a .npy file
c=np.load("numpy_pandas_revision.npy")
print(c)
print('*********************')

#np.loadtxt() function is used to load numpy array from .txt file. We need to give delimiter
d=np.loadtxt("numpy_pandas_revision.txt",delimiter='---')
print(d)

[[3 2 1]
 [6 4 5]]
*********************
[[3. 2. 1.]
 [6. 4. 5.]]


In [11]:
#pandas
#creating data frame from dictionary of list
a={"id":[1,2,3,4,5,6],"name":["shashank","rashmi","prathap","sushmitha","savitha","kavitha"],"work":["not working","working","not working","working","working","not working"]}
df=pd.DataFrame(a)
print(df)
print('*********************')
#creating data frame from list of dictionary
b=[{"id":1,"name":"shashank","age":24},{"id":2,"name":"divya","age":25},{"id":3,"name":"ramya","age":23},{"id":4,"name":"kavya","age":21}]
df1=pd.DataFrame(b)
print(df1)


   id       name         work
0   1   shashank  not working
1   2     rashmi      working
2   3    prathap  not working
3   4  sushmitha      working
4   5    savitha      working
5   6    kavitha  not working
*********************
   id      name  age
0   1  shashank   24
1   2     divya   25
2   3     ramya   23
3   4     kavya   21


In [12]:
#Reading data from existing files of different format csv,tsv,json,excel,sql
#<variable>=pd.read_json("<file_name>.json")
#<variable>=pd.read_csv("<file_name>.tsv",sep="\t")
#<variable>=pd.read_excel("<file_name>.xlsx")
#<variable>=pd.read_sql(<qry>,<connection>)
data_frame=pd.read_csv("BangaloreTopCompanies.csv")
data_frame



Unnamed: 0             CompanyName  Rating Reviews Salaries   Jobs  \
0             0               Accenture     4.1    1.5L    78.6T  27.3T   
1             1                Deloitte     4.1      1L      34T  35.3T   
2             2           Cisco Systems     4.4   31.7T       8T    438   
3             3       Dell Technologies     4.3   33.3T     9.9T    136   
4             4               Microsoft     4.3   49.7T     9.9T   1.6T   
..          ...                     ...     ...     ...      ...    ...   
495         495         Orange Business     4.0    2.3T      647   1.5T   
496         496               ninjacart     4.3    1.1T       1T     68   
497         497           Atlas Systems     4.8     245       98     14   
498         498        Indian Air Force     4.7     614      651     --   
499         499  Intellect Design Arena     4.2      2T     1.6T     15   

                                              Location  \
0                                            Bengaluru   
1                                            Bengaluru   
2                                            Bengaluru   
3                                            Bengaluru   
4                                            Bengaluru   
..                                                 ...   
495                                          Bengaluru   
496  WeWork Vaishnavi Signature, No. 78/9, Outer Ri...   
497  Level 15, Concorde towers, UB City, 1 Vittal M...   
498                                          Bengaluru   
499                                          Bengaluru   

                                    Industry  \
0                        Business Consulting   
1                           Accounting & Tax   
2    Enterprise Software & Network Solutions   
3    Information Technology Support Services   
4              Computer Hardware Development   
..                                       ...   
495  Enterprise Software & Network Solutions   
496  Information Technology Support Services   
497  Information Technology Support Services   
498             National Services & Agencies   
499            Computer Hardware Development   

                                           Description  
0    Growing customer expectations. Market-Shaping ...  
1    Deloitte provides industry-leading audit and a...  
2    #WeAreCisco, where each person is unique. We b...  
3    We believe that each of us has the power to ma...  
4    Our drive to change the world unites us! Micro...  
..                                                 ...  
495                                                NaN  
496  Ninjacart is India’s largest B2B fresh produce...  
497  Atlas Systems Inc. is a leading technology inn...  
498                                                NaN  
499  Intellect Design Arena Ltd, a cloud-native, fu...  

[500 rows x 9 columns]

In [13]:
#exploring data
#describe() is a function in data frame which is used to perform mathematical opertaion on numerical features of data frame and it will display it
#info() is the function in pandas which is used to display the information reagarding features present in the data frame
#shape is attribute in pandas which will describe how many rows and columns present in data frame i.e.,(row,column)
#size is attribute in pandas which will describe how many elements are present in total rows and columns of the data frame i.e.,rows*col
#ndim is attribute in pandas which will give the dimension of data frame i.e, 2 dimension always
#columns is an attribute in pandas which will five all the column names of the data frame in list
#head() is function in pandas which will give starting 5 rows from data frame by default or n number of rows but we need to specify as an argument 
#tail() is function in pandas which will give ending 5 rows from data frame by default or n number of rows but we need to specify as an argument 
df=pd.read_csv("BangaloreTopCompanies.csv")
print(df.describe())
print('*********************')
print(df.info())
print('*********************')
print(df.shape)
print('*********************')
print(df.size)
print('*********************')
print(df.ndim)
print('*********************')
print(df.columns)
print('*********************')
print(df.head(10))
print('*********************')
print(df.tail(10))

       Unnamed: 0      Rating
count  500.000000  500.000000
mean   249.500000    4.157200
std    144.481833    0.177852
min      0.000000    2.800000
25%    124.750000    4.000000
50%    249.500000    4.100000
75%    374.250000    4.200000
max    499.000000    4.800000
*********************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Unnamed: 0   500 non-null    int64  
 1   CompanyName  500 non-null    object 
 2   Rating       500 non-null    float64
 3   Reviews      500 non-null    object 
 4   Salaries     500 non-null    object 
 5   Jobs         500 non-null    object 
 6   Location     500 non-null    object 
 7   Industry     452 non-null    object 
 8   Description  407 non-null    object 
dtypes: float64(1), int64(1), object(7)
memory usage: 35.3+ KB
None
*********************
(500, 9)
*********************
4500
****************

In [14]:
#selection and indexing
df=pd.read_csv("BangaloreTopCompanies.csv")
#selecting single column
print(df["CompanyName"])
print('*********************')

#selecting multiple columns
print(df[["CompanyName","Rating","Location"]])
print('*********************')

#selecting rows using index
print(df[10:13])
print('*********************')

#accesing specific element by using label using loc[]
print(df.loc[10,"CompanyName"])
print('*********************')

print(df.loc[10,["CompanyName","Location"]])
print('*********************')

#accesing specific element by using index using iloc[]
print(df.iloc[490,1])
print('*********************')

print(df.iloc[490:499,1:4])




0                   Accenture
1                    Deloitte
2               Cisco Systems
3           Dell Technologies
4                   Microsoft
                ...          
495           Orange Business
496                 ninjacart
497             Atlas Systems
498          Indian Air Force
499    Intellect Design Arena
Name: CompanyName, Length: 500, dtype: object
*********************
                CompanyName  Rating  \
0                 Accenture     4.1   
1                  Deloitte     4.1   
2             Cisco Systems     4.4   
3         Dell Technologies     4.3   
4                 Microsoft     4.3   
..                      ...     ...   
495         Orange Business     4.0   
496               ninjacart     4.3   
497           Atlas Systems     4.8   
498        Indian Air Force     4.7   
499  Intellect Design Arena     4.2   

                                              Location  
0                                            Bengaluru  
1                  

In [15]:
#filtering 
df=pd.read_csv("BangaloreTopCompanies.csv")
#filtering based on single condition
print(df[df["Location"]=='Bengaluru'])
print('*********************')

#filtering based on multiple condition with and ,or operators
print(df[(df["Rating"]==4.1)|(df["Location"]=='Bengaluru')])
print('*********************')

print(df[(df["Industry"]=="Business Consulting")&(df["Location"]=='Bengaluru')])
print('*********************')

print(df.query("Rating==4.1 or Location=='Bengaluru'"))
print('*********************')

print(df.query("Rating==4.1 and Location=='Bengaluru'"))
print('*********************')


#filtering nan rows
print(df[df["CompanyName"].isna()])
print('*********************')

print(df[df["CompanyName"].notna()])
print('*********************')

#fetching rows with more than one nan in present in data frame
print(df[df.isna().sum(axis=1)>=1])


     Unnamed: 0             CompanyName  Rating Reviews Salaries   Jobs  \
0             0               Accenture     4.1    1.5L    78.6T  27.3T   
1             1                Deloitte     4.1      1L      34T  35.3T   
2             2           Cisco Systems     4.4   31.7T       8T    438   
3             3       Dell Technologies     4.3   33.3T     9.9T    136   
4             4               Microsoft     4.3   49.7T     9.9T   1.6T   
..          ...                     ...     ...     ...      ...    ...   
493         493         Narayana Health     4.1     313      337      1   
494         494              Exide Life     4.1     302      342      2   
495         495         Orange Business     4.0    2.3T      647   1.5T   
498         498        Indian Air Force     4.7     614      651     --   
499         499  Intellect Design Arena     4.2      2T     1.6T     15   

      Location                                 Industry  \
0    Bengaluru                      Busi

In [16]:
#data cleaning
df=pd.read_csv("BangaloreTopCompanies.csv")
#dropna() is function in pandas which will remove the rows from data frame if one nan is present
print(df.dropna())
print('*********************')

print(df.dropna(subset=["Description"]))
print('*********************')

print(df.dropna(thresh=8))
print('*********************')

#drop() is function in pandas which will remove rows and columns with specified axis with column label for column and row index for row
print(df.drop("Unnamed: 0",axis=1))
print('*********************')

print(df.drop(1,axis=0))
print('*********************')

#replace is function in pandas which is used to change the old value into new value with respect to entire data frame and also specified feature of a data frame
print(df.replace("Bengaluru","Bangalore"))
print('*********************')

df["Location"]=df["Location"].replace("Bangalore","Bengaluru")
print(df)
print('*********************')

#rename is function pandas which is used to change names of columns  
print(df.rename(columns={"CompanyName":"company_name"}))
print('*********************')

#sort_values is function in pandas which is used to sort the data frame by specified columns
print(df.sort_values(by=["CompanyName","Rating"]))
print('*********************')

print(df.sort_index())

     Unnamed: 0             CompanyName  Rating Reviews Salaries   Jobs  \
0             0               Accenture     4.1    1.5L    78.6T  27.3T   
1             1                Deloitte     4.1      1L      34T  35.3T   
2             2           Cisco Systems     4.4   31.7T       8T    438   
3             3       Dell Technologies     4.3   33.3T     9.9T    136   
4             4               Microsoft     4.3   49.7T     9.9T   1.6T   
..          ...                     ...     ...     ...      ...    ...   
488         488               Jumbotail     4.0     198      180     55   
491         491               Travelers     4.1    5.6T       93    548   
496         496               ninjacart     4.3    1.1T       1T     68   
497         497           Atlas Systems     4.8     245       98     14   
499         499  Intellect Design Arena     4.2      2T     1.6T     15   

                                              Location  \
0                                        

In [17]:
#changing type of the column data
df=pd.read_csv("BangaloreTopCompanies.csv")
df['Rating']=df['Rating'].astype("str")
print(df['Rating'].dtype)


object


In [18]:
#groupby() is a function in pandas which is used to group the categorical features and perform aggregate operations as needed with help of agg() function
#after doing groupby() to the df[<column>] it will return a groupby object. Later we can apply agg() function to perform aggregate operations with respect to another column.
a={"id":[1,2,3,4,5,6],"Name":["shashank","rashmi","prathap","sushmitha","savitha","kavitha"],"work":["not working","working","not working","working","working","not working"],"gender":["M","F","M","F","F","F"]}
df1 = pd.DataFrame(a)
b=df1.groupby("gender")
print(b.agg({"id":"count"}))
print('*********************')


#pivot_table() is a function in pandas used to perform the same operation as groupby in a simple way.
print(df1.pivot_table(index='gender',values='id',aggfunc='count'))

        id
gender    
F        4
M        2
*********************
        id
gender    
F        4
M        2


In [19]:
# pd.concat() is a function in pandas used to concatenate two dataframes into a single dataframe with reference to axis i.e., axis=0 or 1
b=[{"id":1,"name":"shashank","age":24},{"id":2,"name":"divya","age":25},{"id":3,"name":"rashmi","age":23},{"id":4,"name":"kavya","age":21}]
df2 = pd.DataFrame(b)
print(pd.concat([df1,df2],axis=1))
print('*********************')


#pd.merge() is a function in pandas used to merge two dataframes into a single dataframe with related columns. Merge will work same as SQL joins.
print(pd.merge(df1,df2,right_on='name',left_on='Name'))
print('*********************')

print(pd.merge(df1,df2,right_on='name',left_on='Name',how='outer'))
print('*********************')

print(pd.merge(df1,df2,right_on='name',left_on='Name',how='right'))
print('*********************')

print(pd.merge(df1,df2,right_on='name',left_on='Name',how='left'))

   id       Name         work gender   id      name   age
0   1   shashank  not working      M  1.0  shashank  24.0
1   2     rashmi      working      F  2.0     divya  25.0
2   3    prathap  not working      M  3.0    rashmi  23.0
3   4  sushmitha      working      F  4.0     kavya  21.0
4   5    savitha      working      F  NaN       NaN   NaN
5   6    kavitha  not working      F  NaN       NaN   NaN
*********************
   id_x      Name         work gender  id_y      name  age
0     1  shashank  not working      M     1  shashank   24
1     2    rashmi      working      F     3    rashmi   23
*********************
   id_x       Name         work gender  id_y      name   age
0   1.0   shashank  not working      M   1.0  shashank  24.0
1   2.0     rashmi      working      F   3.0    rashmi  23.0
2   3.0    prathap  not working      M   NaN       NaN   NaN
3   4.0  sushmitha      working      F   NaN       NaN   NaN
4   5.0    savitha      working      F   NaN       NaN   NaN
5   6.0

In [20]:
#apply() is a function in pandas which is used to apply the custom function to the dataframe column and also to the entire dataframe

def change_gender_value(gender):
    if gender=='M':
        return 'Male'
    elif gender=='F':
        return 'Female'
    else:
        return 'Other'

df1['gender']=df1['gender'].apply(change_gender_value)
print(df1)

   id       Name         work  gender
0   1   shashank  not working    Male
1   2     rashmi      working  Female
2   3    prathap  not working    Male
3   4  sushmitha      working  Female
4   5    savitha      working  Female
5   6    kavitha  not working  Female
